spring:
  application:
    name: icalendar-vevent
  datasource:
    url: jdbc:postgresql://localhost:5432/appdb
    username: appuser
    password: appsecret
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: validate   # use 'validate' ou 'none' em produção
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html